name: movies_watcher_fschmatz
description: "Track movies"
publish_to: 'none'
version: 1.4.3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  http:
  fluttertoast:
  easy_dynamic_theme:
  shared_preferences:
  share_plus: ^10.0.0
  sqflite:
  path_provider:
  dynamic_value:
  jiffy:
  dynamic_color: ^1.7.0
  cupertino_icons: ^1.0.2
  image_picker:
  flutter_image_compress: ^2.3.0
  permission_handler: ^11.3.0
  flutter_fadein: ^2.0.0
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/
