name: movies_watcher_fschmatz
description: "Track movies"
publish_to: 'none'
version: 1.1.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  http:
  fluttertoast:
  easy_dynamic_theme:
  shared_preferences:
  share:
  sqflite:
  path_provider:
  dynamic_value:
  jiffy:
  animations:
  dynamic_color: ^1.6.9
  cupertino_icons: ^1.0.2
  flutter_native_image:
  flutter_image_compress: ^1.1.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
