name: movies_watcher_fschmatz
description: "Track movies"
publish_to: 'none'
version: 1.5.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.4.0
  fluttertoast: ^8.2.12
  easy_dynamic_theme: ^2.3.1
  shared_preferences: ^2.5.3
  share_plus: ^10.0.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  dynamic_value: ^3.0.0
  jiffy: ^6.4.3
  dynamic_color: ^1.7.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  permission_handler: ^11.3.0
  flutter_fadein: ^2.0.0
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/
